[package]
name = "Cherry-o"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
indicatif = "0.17.11"
num-format = "0.4.4"
rand = "0.8.5"
